#!/bin/bash

cd "$(dirname "$0")"

NAME=homekube-etcd
DATA_DIR=/srv/etcd

TLS_ARGS=()
for file in api-server.pem api-server-key.pem root.pem; do
	TLS_ARGS+=(-v "$(pwd)/../ca/$file:/$file")
done

if docker container inspect "$NAME" >/dev/null 2>&1; then
	echo "Killing existing container..."
	docker stop "$NAME"
fi

# ALLOW_NONE_AUTHENTICATION is safe because we're using client certs
docker run --rm -d \
	--name homekube-etcd \
	-e ALLOW_NONE_AUTHENTICATION=yes \
	-v "$DATA_DIR:/mnt" \
	-v "$(pwd)/etcd.conf.yaml:/etcd.conf.yml" \
	"${TLS_ARGS[@]}" \
	--publish 2379:2379 \
	'quay.io/coreos/etcd:v3.5.4' \
	etcd --config-file /etcd.conf.yml
