#!/bin/bash

set -eu

NAME="${1?Name required}"

jq --arg NAME "$NAME" -n '
	{
		charm: "192.168.42.2",
	}[$NAME] as $ip
	| {
		"CN": "system:node:\($NAME)",
		"key": {
			"algo": "rsa",
			"size": 2048
		},
		"names": [
			{
				"O": "system:nodes"
			}
		],
		"hosts": [
			$NAME,
			$ip // empty
		],
	}
'
